return PlaceObj('ModDef', {
	'title', "JA3 Tactician Enhanced",
	'description', '[h3]INTRO[/h3]\n[quote]"⚔️[url=https://steamcommunity.com/sharedfiles/filedetails/?id=3042581131]Tactician Enhanced[/url] might be one of the last mods may cure your JA3 gaming impotence while being in thousands of hours NG+ and boring with those stupid enemy bots. Explore tons of fresh gunfight features and competitively cunning & devious enemies in one-stop solution!🛡️"[/quote]\n\n[h3]FEATURES[/h3]\n[quote]🎬Preview CORE features in TWO short video Clips:\n[list][*][url=https://youtu.be/RUeCT-vD7Gw]0:00 Spotter Reconnaissance Tactics + 1:11 Night Illumination Tactics + 1:42 Combat Stealth and Ambush Tactics +  3:04 Enemy CQC Tactics (🖱️Click to view)[/url].\n[*][url=https://youtu.be/g20vAlUoXgo]0:00 Advanced Cover Protection System + 1:49 Area of Fire Suppression System + 3:17 Enemy Comprehensive Combat System (🖱️Click to view)[/url].[/list]\n🛠️Mod features are controlled via [url=https://images.steamusercontent.com/ugc/17631046534119317659/705702D58CA9B4D243292D522F5345DB91BF4E0C/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false]MOD OPTIONS (🖱️Click to view).[/url]\n\n🎲[url=https://images.steamusercontent.com/ugc/9422238173307965455/E116A81B2C1E76467B461E90041261BFC2959E41/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false]Blue \\ Pink \\ Red (🖱️Click to view)[/url] colored mod options are considered to adaptively meet your challenging expectation once you\'ve mastered the Tactician Enhanced logic deeply or your merc teams are well armed and reach high level with meta-built perks.\n(i.e. the default mod settings are prepared only for Tactician Enhanced Rookies)\n\n💾Turn on these challenging mod options will bring new enemy tactics and features at the next turn in combat or enter a new sector so current save-game friendly.🎮\n(i.e. you don\'t need to restart a new campaign at all)[/quote]\n\n[h3]COMPATIBILITY[/h3]\n[quote]⚠️YOU CAN TURN OFF SOME [url=https://images.steamusercontent.com/ugc/17631046534119317659/705702D58CA9B4D243292D522F5345DB91BF4E0C/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false]MOD OPTIONS (🖱️)[/url] (TACTICAL ENEMY PRESETS / TACTICAL AIM PRESETS / STOCK DATA OVERHAUL) to play Tactician Enhanced with other popular mods:\n[list][*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3586181969]Vanilla Redux: Weapons, Mercs & Progression Rebalance[/url]\n[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3021320057]Rato\'s Gameplay Balance and Overhaul 3[/url]\n[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3023672178]Tons of Guns[/url]\n[*]Basic Crafting Economy Suite (Latest [B.C.E.] edition at Nexus mods)[/list]\n❗️Turn off those mod options are NOT required but just allow other overhaul mods take control the core gunfight features towards their concept more, while at the cost of losing the CORE logic of Tactician Enhanced.\n(i.e. you decide what you prefer but all enemies combat tactics will be much less optimal due to completely different logic rules)\n\n⚙️PERFECTLY SUPPORT [url=https://steamcommunity.com/sharedfiles/filedetails/?id=3090261695]Masters of War[/url], [url=https://steamcommunity.com/sharedfiles/filedetails/?id=3155016246]The Awakening of the Eastern Dragon[/url], [url=https://steamcommunity.com/sharedfiles/filedetails/?id=3157842808]More Armor[/url], [url=https://steamcommunity.com/sharedfiles/filedetails/?id=3178380968]Revised Tactical Gear & Mags II[/url], [url=https://steamcommunity.com/sharedfiles/filedetails/?id=3309452207]Zulib Weapons Core[/url].\n\n🚨DEFENITELY NEVER USE THIS MOD WITH OTHER ENEMY AI OVERHAUL MODS!\n(such as Rato\'s AI, Tactical AI, Tactical Enemy, etc. otherwise your game will be UNPLAYABLE)\n\n❌NOT RECOMMEND USE THIS MOD WITH OTHER SUPPRESSION OR OVERWATCH MODS!\n(such as Pinned Down, Smart Overwatch, etc. otherwise AOE suppression, illumination and reconnaissance features become malfunction)[/quote]\n\n[b]🐉华人铁友可加铁血联盟3【🐧QQ交流群：881710876】提供反馈和建议。[/b]',
	'image', "Mod/JA3_TacticianEnhanced/Images/JA3_TacticianEnhanced.png",
	'last_changes', "Remake Dice-Roll [Sector Ambusher] Logic to avoid potential bugs. -- Thanks for bug reports from TE Core Community.",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "JA3_CommonLib",
			'title', "JA3_CommonLib",
			'version_major', 1,
			'version_minor', 9,
		}),
		PlaceObj('ModDependency', {
			'id', "LDCUAE",
			'title', "C-UAE Cross-Mod Universal Armament Expansion",
			'version_major', 4,
			'version_minor', 5,
		}),
	},
	'id', "JA3_TacticianEnhanced",
	'author', "LionCat",
	'version_major', 4,
	'version_minor', 1,
	'version', 11195,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"CharacterEffect/TEActivation.lua",
		"CharacterEffect/TacticalEnemy.lua",
		"CharacterEffect/TacticalAmbusher.lua",
		"CharacterEffect/TacticalBOW.lua",
		"CharacterEffect/TacticalTutorial.lua",
		"CharacterEffect/EnemyFullAlert.lua",
		"CharacterEffect/EnemyCQCReaction.lua",
		"CharacterEffect/EnemyBioInfection.lua",
		"CharacterEffect/TutorialMinion.lua",
		"CharacterEffect/InnerInfoRemake.lua",
		"CharacterEffect/LightStepRemake.lua",
		"CharacterEffect/GlobalSightRange.lua",
		"CharacterEffect/GlobalVisualContact.lua",
		"CharacterEffect/GlobalCamouflage.lua",
		"CharacterEffect/GlobalReconnaissance.lua",
		"CharacterEffect/GlobalEnemySpotted.lua",
		"CharacterEffect/GlobalCombatConcealed.lua",
		"CharacterEffect/GlobalCoverProtection.lua",
		"CharacterEffect/RealHeavyWounds.lua",
		"CharacterEffect/SuppressionShocked.lua",
		"CharacterEffect/SuppressionArtilleryCalled.lua",
		"CharacterEffect/DistractingRetaliationCounter.lua",
		"CharacterEffect/SuppressingRetaliationCounter.lua",
		"CharacterEffect/ThrowingRetaliationCounter.lua",
		"CharacterEffect/LauncherRetaliationCounter.lua",
		"CharacterEffect/MortarRetaliationCounter.lua",
		"CharacterEffect/ArtilleryRetaliationCounter.lua",
		"CharacterEffect/SmokeCoverCounter.lua",
		"CharacterEffect/ReinforcementProtection.lua",
		"CharacterEffect/AmbusherProtection.lua",
		"CharacterEffect/BOWSummoned.lua",
		"CharacterEffect/BOWRitualsCD.lua",
		"CharacterEffect/IlluminationSpotted.lua",
		"CharacterEffect/ReconnaissanceSpottedBad.lua",
		"CharacterEffect/ReconnaissanceSpottedGood.lua",
		"CharacterEffect/ReconnaissanceSpottedExcellent.lua",
		"CharacterEffect/ReconnaissanceSpottedNVG.lua",
		"InventoryItem/TE_Binoculars.lua",
		"UnitData/InfectedSoldier.lua",
		"UnitData/InfectedLicker.lua",
		"UnitData/InfectedHyena.lua",
		"UnitData/InfectedCrocodile.lua",
		"UnitData/BOWSuperMK1.lua",
		"UnitData/BOWSuperMK2.lua",
		"InventoryItem/BOW_SharpenedJaws.lua",
		"InventoryItem/BOW_HardenedSkin.lua",
		"Code/TE_AIArchetype.lua",
		"Code/TE_Mechanism.lua",
		"Code/TE_GunFightRework.lua",
		"Code/TE_ArmorRework.lua",
		"Code/TE_CaliberRework.lua",
		"Code/TE_FirearmsRework.lua",
		"Code/TE_ComponentsRework.lua",
		"Code/TE_ExplosiveRework.lua",
		"Code/TE_ExplosiveAOE.lua",
		"Code/TE_AIM-Presets.lua",
		"Code/TE_PerksEffects.lua",
		"Code/TE_DiceRoll.lua",
		"Code/TE_HellGate.lua",
		"Code/TE_Darkness.lua",
		"Code/TE_BagStacks.lua",
		"Code/TE_Utils.lua",
		"Code/TE_C-UAE.lua",
	},
	'loctables', {
		{
			filename = "Mod/JA3_TacticianEnhanced/Local/TE_Schinese.csv",
			language = "Schinese",
		},
	},
	'default_options', {
		Auto_Resolve = "200%",
		Darkness_Level = "150%",
		DiceRoll_Event = "<GameTerm('TE_OFF')>",
		Explosion_Resistance = "60%",
		Gunfight_Rework = true,
		Hell_Gate = "<GameTerm('TE_OFF')>",
		Merc_Immortal = true,
		Overwatch_Cone = true,
		Projectile_Velocity = "200%",
		Real_Lethal = false,
		SilencerFX_Disabler = false,
		SquadBag_MaxStacks = false,
		Tactical_AIM = true,
		Tactical_Enemy = true,
		Tactical_Hardcore = "<GameTerm('TE_OFF')>",
		Tactical_Legion = true,
		Tactical_Tutorial = true,
		Unaware_Sight = "80%",
	},
	'has_data', true,
	'saved', 1779634895,
	'code_hash', -5933034300268207019,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_E1",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_E2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_E3",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_E4",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_A1",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_A2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_A3",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_A4",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_B1",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_B2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_M1",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Legion_M2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Army_E1",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Adonis_E1",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Adonis_E2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Tactical_Adonis_A1",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Infected_Hyena_01",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Infected_Hyena_02",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Infected_Hyena_03",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Infected_Hyena_04",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Infected_Hyena_05",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Infected_Crocodile_01",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Infected_Crocodile_02",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Infected_Crocodile_03",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Infected_Legion_Soldier",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "HellGate_Super_MK1",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "HellGate_Super_MK2",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "TEActivation",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "TacticalEnemy",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "TacticalAmbusher",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "TacticalBOW",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "TacticalTutorial",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "EnemyFullAlert",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "EnemyCQCReaction",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "EnemyBioInfection",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "TutorialMinion",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "InnerInfoRemake",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "LightStepRemake",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "LightStep",
			'Prop', "Description",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "EyesOnTheBack",
			'Prop', "Description",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "DanceForMe",
			'Prop', "Description",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "BulletHell",
			'Prop', "Description",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "GlobalSightRange",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "GlobalVisualContact",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "GlobalCamouflage",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "GlobalReconnaissance",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "GlobalEnemySpotted",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "GlobalCombatConcealed",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "GlobalCoverProtection",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "RealHeavyWounds",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "SuppressionShocked",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "SuppressionArtilleryCalled",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "DistractingRetaliationCounter",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "SuppressingRetaliationCounter",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ThrowingRetaliationCounter",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "LauncherRetaliationCounter",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "MortarRetaliationCounter",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ArtilleryRetaliationCounter",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "SmokeCoverCounter",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ReinforcementProtection",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "AmbusherProtection",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "BOWSummoned",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "BOWRitualsCD",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "IlluminationSpotted",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ReconnaissanceSpottedBad",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ReconnaissanceSpottedGood",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ReconnaissanceSpottedExcellent",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ReconnaissanceSpottedNVG",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TE_Binoculars",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "InfectedSoldier",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "InfectedLicker",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "InfectedHyena",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "InfectedCrocodile",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "BOWSuperMK1",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "BOWSuperMK2",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "BOW_SharpenedJaws",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "BOW_HardenedSkin",
			'ClassDisplayName', "Inventory item",
		}),
	},
	'steam_id', "3042581131",
	'TagBalancing&Difficulty', true,
	'TagCombat&AI', true,
	'TagEnemies', true,
	'TagGameSettings', true,
	'TagMercs', true,
	'TagPerks&Talents&Skills', true,
	'TagQuest&Campaigns', true,
	'TagWeapons&Items', true,
})