--All Loots to Squad-Bag & Max-Stacks
local TE_SquadBag_Zulib = {
    "_9mm_Basic",                     
    "_9x18_Basic",                    
    "_9x39_Basic",                    
    "_22LR_Basic",                    
    "_280British_Basic",              
    "_300Blackout_Basic",             
    "_300WinMag_Basic",               
    "_303_Basic",                     
    "_308Win_Basic",                  
    "_30_60_Basic",                   
    "_32ACP_Basic",                   
    "_32HRMAG_Basic",                 
    "_338_Lapua_Magnum_Basic",        
    "_357MAG_Basic",                  
    "_38SP_Basic",                    
    "_380ACP_Basic",                  
    "_40SW_Basic",                    
    "_408_ChayTac_Basic",             
    "_44AMP_Basic",                   
    "_44CAL_Basic",                   
    "_44MAG_Basic",                   
    "_45ACP_Basic",                       
--  "MoW_45ACP_Basic",               
    "_50AE_Basic",                    
    "_4_6x30_Basic",                  
    "_4_7x33_Basic",                  
    "_5_45x39_Basic",                 
    "_556_Basic",                     
    "_5_7x28_Basic",                  
--  "_58CHN_Basic",                   
    "_6_5Creedmoor_Basic",            
    "_6_5Grendel_Basic",              
    "_7_5x54_Basic",                  
    "_762WP_Basic",                   
    "_762NATO_Basic",                 
    "_7_62x25_Basic",                 
--  "MoW_762Tok_Basic",                 
    "_7_62x54_Basic",                 
    "_7_65x21_Basic",                 
    "_7_92x33_Basic",                 
    "_7_92x57_Basic",                 
--  "_86CHN_AP",                   
    "_9mm_AP",                     
    "_9x18_AP",                    
    "_9x39_AP",                    
    "_22LR_AP",                    
    "_280British_AP",              
    "_300Blackout_AP",             
    "_300WinMag_AP",               
    "_303_AP",                     
    "_308Win_AP",                  
    "_30_60_AP",                   
    "_32ACP_AP",                   
    "_32HRMAG_AP",                 
    "_338_Lapua_Magnum_AP",        
    "_357MAG_AP",                  
    "_38SP_AP",                    
    "_380ACP_AP",                  
    "_40SW_AP",                    
    "_408_ChayTac_AP",             
    "_44AMP_AP",                   
    "_44CAL_AP",                   
    "_44MAG_AP",                   
    "_45ACP_AP",                   
    "_50AE_AP",                    
    "_4_6x30_AP",                  
    "_4_7x33_AP",                  
    "_5_45x39_AP",                 
    "_556_AP",                     
    "_5_7x28_AP",                  
--  "_58CHN_AP",                   
    "_6_5Creedmoor_AP",            
    "_6_5Grendel_AP",              
    "_7_5x54_AP",                  
    "_762WP_AP",                   
    "_762NATO_AP",                 
    "_7_62x25_AP",                 
    "_7_62x54_AP",                 
    "_7_65x21_AP",                 
    "_7_92x33_AP",                 
    "_7_92x57_AP",                 
--  "_86CHN_AP",                   
    "_9mm_HP",                     
    "_9x18_HP",                    
    "_9x39_HP",                    
    "_22LR_HP",                    
    "_280British_HP",              
    "_300Blackout_HP",             
    "_300WinMag_HP",               
    "_303_HP",                     
    "_308Win_HP",                  
    "_30_60_HP",                   
    "_32ACP_HP",                   
    "_32HRMAG_HP",                 
    "_338_Lapua_Magnum_HP",        
    "_357MAG_HP",                  
    "_38SP_HP",                    
    "_380ACP_HP",                  
    "_40SW_HP",                    
    "_408_ChayTac_HP",             
    "_44AMP_HP",                   
    "_44CAL_HP",                   
    "_44MAG_HP",                   
    "_45ACP_HP",                    
--  "MoW_45ACP_HP",                  
    "_50AE_HP",                    
    "_4_6x30_HP",                  
    "_4_7x33_HP",                  
    "_5_45x39_HP",                 
    "_556_HP",                     
    "_5_7x28_HP",                  
--  "_58CHN_HP",                   
    "_6_5Creedmoor_HP",            
    "_6_5Grendel_HP",              
    "_7_5x54_HP",                  
    "_762WP_HP",                   
    "_762NATO_HP",                 
    "_7_62x25_HP",                 
    "_7_62x54_HP",                 
    "_7_65x21_HP",                 
    "_7_92x33_HP",                 
    "_7_92x57_HP",                 
--  "_86CHN_HP",                   
    "_9mm_Match",                  
    "_9x18_Match",                 
    "_9x39_Match",                 
    "_22LR_Match",                 
    "_280British_Match",           
    "_300Blackout_Match",          
    "_300WinMag_Match",            
    "_303_Match",                  
    "_308Win_Match",               
    "_30_60_Match",                
    "_32ACP_Match",                
    "_32HRMAG_Match",              
    "_338_Lapua_Magnum_Match",     
    "_357MAG_Match",               
    "_38SP_Match",                 
    "_380ACP_Match",               
    "_40SW_Match",                 
    "_408_ChayTac_Match",          
    "_44AMP_Match",                
    "_44CAL_Match",                
    "_44MAG_Match",                
    "_45ACP_Match",                
    "_50AE_Match",                 
    "_4_6x30_Match",               
    "_4_7x33_Match",               
    "_5_45x39_Match",              
    "_556_Match",                  
    "_5_7x28_Match",               
--  "_58CHN_Match",                
    "_6_5Creedmoor_Match",         
    "_6_5Grendel_Match",           
    "_7_5x54_Match",               
    "_762WP_Match",                
    "_762NATO_Match",              
    "_7_62x25_Match",              
    "_7_62x54_Match",              
    "_7_65x21_Match",              
    "_7_92x33_Match",              
    "_7_92x57_Match",              
--  "_86CHN_Match",                
    "_9mm_Tracer",                 
    "_9x18_Tracer",                
    "_9x39_Tracer",                
    "_22LR_Tracer",                
    "_280British_Tracer",          
    "_300Blackout_Tracer",         
    "_300WinMag_Tracer",           
    "_303_Tracer",                 
    "_308Win_Tracer",              
    "_30_60_Tracer",               
    "_32ACP_Tracer",               
    "_32HRMAG_Tracer",             
    "_338_Lapua_Magnum_Tracer",    
    "_357MAG_Tracer",              
    "_38SP_Tracer",                
    "_380ACP_Tracer",              
    "_40SW_Tracer",                
    "_408_ChayTac_Tracer",         
    "_44AMP_Tracer",               
--  "_44CAL_Tracer",               
    "_44MAG_Tracer",               
    "_45ACP_Tracer",               
    "_50AE_Tracer",                
    "_4_6x30_Tracer",              
    "_4_7x33_Tracer",              
    "_5_45x39_Tracer",             
    "_556_Tracer",                 
    "_5_7x28_Tracer",              
--  "_58CHN_Tracer",               
    "_6_5Creedmoor_Tracer",        
    "_6_5Grendel_Tracer",          
    "_7_5x54_Tracer",              
    "_762WP_Tracer",               
    "_762NATO_Tracer",             
    "_7_62x25_Tracer",             
    "_7_62x54_Tracer",             
    "_7_65x21_Tracer",             
    "_7_92x33_Tracer",             
    "_7_92x57_Tracer",             
--  "_86CHN_Tracer",               
    "_9mm_Shock",                  
    "_32HRMAG_Shock",              
    "_44AMP_Shock",                
    "_44CAL_Shock",                
    "_44MAG_Shock",                
    "_50AE_Shock",                 
    "_9mm_Subsonic",               
    "_300Blackout_Subsonic",       
    "_44AMP_Subsonic",             
    "_44CAL_Subsonic",             
    "_44MAG_Subsonic",             
    "_45ACP_Subsonic",        
	"_20x82_Basic",     
	"_20x82_HE",
	"_20x82_SLAP",
	"_20x81_Incendiary",
	"_50BMG_Basic",
	"_50BMG_HE",
	"_50BMG_SLAP",
	"_50BMG_Incendiary",
	"_12gauge_Breacher",
	"_12gauge_Buckshot",
	"_12gauge_Flechette",
	"_12gauge_Saltshot",
	"_22mm_NATO_Frag",
	"_22mm_NATO_Gas",
	"_22mm_NATO_Smoke",
	"_22mm_WP_Frag",
	"_22mm_WP_Gas",
	"_22mm_WP_Smoke",
	"_40mmFragGrenade",
	"_40mmFlashbangGrenade",
	"Warhead_Frag",
	"MortarShell_HE",
	"MortarShell_Gas",
	"MortarShell_Smoke",
	"BigDiamond",
	"ChippedSapphire",
--	"Crowbar",
--	"FirstAidKit",
	"GoldBar",
--	"Lockpick",
--	"Medkit",
--	"Reanimationsset",
	"TinyDiamonds",
--	"Wirecutter",
	"BlackPowder",
	"C4",
	"Coin",
	"CombatStim",
	"Combination_BalancingWeight",
	"Combination_CeramicPlates",
	"Combination_Detonator_Proximity",
	"Combination_Detonator_Remote",
	"Combination_Detonator_Time",
	"Combination_Sharpener",
	"Combination_WeavePadding",
	"Combination_Kompositum58",
	"ConcussiveGrenade",
	"Cookie",
	"CrocodileHide",
	"CrocodileJaws",
	"Detonator",
	"DiamondBriefcase",
	"DiamondNecklace",
	"Diesel",
	"FineSteelPipe",
	"FlareAmmo",
	"FlareStick",
	"FragGrenade",
	"FuelTank",
	"GlowStick",
	"GoldenWatch",
	"HE_Grenade",
	"HerbalMedicine",
	"HyenaJaws",
	"Infected_HardenedSkin",
	"Knife",
	"Knife_Balanced",
	"Knife_Sharpened",
	"Machete",
	"Machete_Balanced",
	"Machete_Sharpened",
	"MedicalReport",
	"Meds",
	"Microchip",
	"MissingItem",
	"Molotov",
	"MoneyBag",
	"Moped",
	"OpticalLens",
	"PaBaggzWill",
	"Pamphlets",
	"Pamphlets_LysRouge",
	"Parts",
	"PETN",
	"PickupTruck",
	"PipeBomb",
--	"PlasmaGun_Crowbar",
	"PowerGenerator",
	"PowerGenerator_Military",
	"ProximityC4",
	"ProximityPETN",
	"ProximityTNT",
	"RemoteC4",
	"RemotePETN",
	"RemoteTNT",
	"ShapedCharge",
	"SkillMag_Agility",
	"SkillMag_Dexterity",
	"SkillMag_Explosives",
	"SkillMag_Health",
	"SkillMag_Leadership",
	"SkillMag_Marksmanship",
	"SkillMag_Mechanical",
	"SkillMag_Medical",
	"SkillMag_Strength",
	"SkillMag_Wisdom",
	"SmokeGrenade",
	"Super_HE_Grenade",
	"TearGasGrenade",
	"TE_Binoculars",
	"TheGreenDiamond",
	"TimedC4",
	"TimedPETN",
	"TimedTNT",
	"TNT",
	"ToxicGasGrenade",
	"TreasureFigurine",
	"TreasureGoldenDog",
	"TreasureIdol",
	"TreasureMask",
	"TreasureTablet",
	"US_Passport",
	"VirusSample",
	"WeirdosMap",
	"Wig",
	"WorkerDiary",
	"WriterDiary",
	"WriterLetter",
	"WriterPage",
}

local TE_SquadBag = {
	"_9mm_Basic",
	"_9mm_AP",
	"_9mm_HP",
	"_9mm_Match",
	"_9mm_Shock",
	"_9mm_Subsonic",
	"_9mm_Tracer",
	"_44CAL_Basic",
	"_44CAL_AP",
	"_44CAL_HP",
	"_44CAL_Match",
	"_44CAL_Shock",
	"_556_Basic",
	"_556_AP",
	"_556_HP",
	"_556_Match",
	"_556_Tracer",
	"_762WP_Basic",
	"_762WP_AP",
	"_762WP_HP",
	"_762WP_Match",
	"_762WP_Tracer",
	"_762NATO_Basic",
	"_762NATO_AP",
	"_762NATO_HP",
	"_762NATO_Match",
	"_762NATO_Tracer",
	"_50BMG_Basic",
	"_50BMG_SLAP",
	"_50BMG_HE",
	"_50BMG_Incendiary",
	"_12gauge_Buckshot",
	"_12gauge_Breacher",
	"_12gauge_Flechette",
	"_12gauge_Saltshot",
	"_40mmFlashbangGrenade",
	"_40mmFragGrenade",
	"Warhead_Frag",
	"MortarShell_HE",
	"MortarShell_Gas",
	"MortarShell_Smoke",
	"BigDiamond",
	"ChippedSapphire",
--	"Crowbar",
--	"FirstAidKit",
	"GoldBar",
--	"Lockpick",
--	"Medkit",
--	"Reanimationsset",
	"TinyDiamonds",
--	"Wirecutter",
	"BlackPowder",
	"C4",
	"Coin",
	"CombatStim",
	"Combination_BalancingWeight",
	"Combination_CeramicPlates",
	"Combination_Detonator_Proximity",
	"Combination_Detonator_Remote",
	"Combination_Detonator_Time",
	"Combination_Sharpener",
	"Combination_WeavePadding",
	"Combination_Kompositum58",
	"ConcussiveGrenade",
	"Cookie",
	"CrocodileHide",
	"CrocodileJaws",
	"Detonator",
	"DiamondBriefcase",
	"DiamondNecklace",
	"Diesel",
	"FineSteelPipe",
	"FlareAmmo",
	"FlareStick",
	"FragGrenade",
	"FuelTank",
	"GlowStick",
	"GoldenWatch",
	"HE_Grenade",
	"HerbalMedicine",
	"HyenaJaws",
	"Infected_HardenedSkin",
	"Knife",
	"Knife_Balanced",
	"Knife_Sharpened",
	"Machete",
	"Machete_Balanced",
	"Machete_Sharpened",
	"MedicalReport",
	"Meds",
	"Microchip",
	"MissingItem",
	"Molotov",
	"MoneyBag",
	"Moped",
	"OpticalLens",
	"PaBaggzWill",
	"Pamphlets",
	"Pamphlets_LysRouge",
	"Parts",
	"PETN",
	"PickupTruck",
	"PipeBomb",
--	"PlasmaGun_Crowbar",
	"PowerGenerator",
	"PowerGenerator_Military",
	"ProximityC4",
	"ProximityPETN",
	"ProximityTNT",
	"RemoteC4",
	"RemotePETN",
	"RemoteTNT",
	"ShapedCharge",
	"SkillMag_Agility",
	"SkillMag_Dexterity",
	"SkillMag_Explosives",
	"SkillMag_Health",
	"SkillMag_Leadership",
	"SkillMag_Marksmanship",
	"SkillMag_Mechanical",
	"SkillMag_Medical",
	"SkillMag_Strength",
	"SkillMag_Wisdom",
	"SmokeGrenade",
	"Super_HE_Grenade",
	"TearGasGrenade",
	"TE_Binoculars",
	"TheGreenDiamond",
	"TimedC4",
	"TimedPETN",
	"TimedTNT",
	"TNT",
	"ToxicGasGrenade",
	"TreasureFigurine",
	"TreasureGoldenDog",
	"TreasureIdol",
	"TreasureMask",
	"TreasureTablet",
	"US_Passport",
	"VirusSample",
	"WeirdosMap",
	"Wig",
	"WorkerDiary",
	"WriterDiary",
	"WriterLetter",
	"WriterPage",
}

if CurrentModOptions["SquadBag_MaxStacks"] then
	if table.find(ModsLoaded, "id", "Tc3ajdY") then
		for _, obj in ipairs(TE_SquadBag_Zulib) do
			table.insert(_G[obj].__parents,"SquadBagItem")
			_G[obj].MaxStacks = 100000
		end
	else
		for _, obj in ipairs(TE_SquadBag) do
			table.insert(_G[obj].__parents,"SquadBagItem")
			_G[obj].MaxStacks = 100000
		end
	end
end

function InventoryStack:GetItemSlotUI()
	return T({0, "<style InventoryItemsCount><cur></style>", cur = self.Amount})
end

function TFormat.bullets(context_obj, bullets, max, icon)
	icon = icon or "<image UI/Icons/Rollover/ammo_placeholder 1400>"
	bullets = bullets or GetBulletCount(context_obj)
	if not bullets then
		return T(994336406701, "<image UI/Icons/Hud/ammo_infinite>")
	end
	
	local max = max or context_obj and context_obj.MagazineSize
	local text = bullets == 0 and "<error><bullets></error>" or "<bullets>"
	if not max then
		return T({
			370913997359,
			text,
			bullets = bullets,
			icon = icon
		})
	else
		text = text .. "/<style InventoryItemsCountMax><max></style>"
		return T({
			text,
			bullets = bullets,
			max = max or 0,
			icon = icon
		})
	end
end