UndefineClass('InfectedLicker')
DefineClass.InfectedLicker = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	comment = "B.O.W. Infected Licker",
	object_class = "UnitData",
	Health = 100,
	Agility = 100,
	Dexterity = 100,
	Strength = 100,
	Wisdom = 5,
	Leadership = 5,
	Marksmanship = 5,
	Mechanical = 5,
	Explosives = 5,
	Medical = 5,
	Name = T(966268321705, --[[ModItemUnitDataCompositeDef InfectedLicker Name]] "Licker"),
	Randomization = true,
	Affiliation = "Secret",
	StartingLevel = 10,
	neutral_retaliate = true,
	archetype = "Brute",
	role = "Stormer",
	CanManEmplacements = false,
	RepositionArchetype = "Scout_LastLocation",
	OpeningAttackType = "PinDown",
	MaxHitPoints = 60,
	StartingPerks = {
		"ZombiePerk",
		"NaturalCamouflage",
		"LightningReactionNPC",
		"FleetingShadow",
		"MakeThemBleed",
		"MeleeTraining",
		"NightOps",
		"BeefedUp",
		"Berserker",
		"Flanker",
		"DeathFromAbove",
		"ColdHeart",
		"BloodlustPerk",
		"HardBlow",
		"BloodScent",
		"Hobbler",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Skeleton_Burnt",
		}),
	},
	Equipment = {
		"BOW_Hunter_Gear",
	},
	gender = "Male",
	infected = true,
}

